sudo: required
services:
  - docker

script:
  - docker build -t emanewere/multi-client-two ./client
  - docker build -t emanewere/multi-nginx-two ./nginx
  - docker build -t emanewere/multi-server-two ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push emanewere/multi-client-two
  - docker push emanewere/multi-nginx-two
  - docker push emanewere/multi-server-two

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker-two"
  env: "multi-docker-two-env"
  bucket_name: "elasticbeanstalk-us-east-1-355782294313"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
